language: R
warnings_are_errors: true
sudo: required
cache: packages

addons:
  apt:
    packages:
    - r-cran-ncdf4

env:
- _R_CHECK_FORCE_SUGGESTS_=0

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
